import type {State} from './types'
import {LiaAvatar} from './LiaAvatar'
import {useLiaRuntime} from './useLiaRuntime'

const labels:Record<State,string>={idle:'Лия рядом',listening:'Слушаю тебя',thinking:'Думаю о запросе',speaking:'Отвечаю тебе',error:'Нужна помощь'}
const quick=['Что ты умеешь?','Составь план на день','Открой мои заметки','Запомни это']

export function App(){
  const runtime=useLiaRuntime()
  const {state,metrics,latency,facts,input,setInput,panel,setPanel,connected,messages,analyser,faceFrame,send,start,stop,submit,cancel}=runtime
  return <main className={`companion ${state}`}><header className="topbar"><div className="wordmark"><span className="wordmark-dot"/>Лия<span> локальный компаньон</span></div><div className="top-center">{connected?'runtime online':'runtime offline'}</div><div className="top-actions"><button onClick={()=>{setPanel(!panel);send({type:'memory_list'})}}>Память · {facts.length}</button><div className="avatar">Л</div></div></header><section className="stage"><div className="stage-glow"/><LiaAvatar state={state} analyser={analyser} faceFrame={faceFrame}/><div className="character-shadow"/><div className="stage-caption"><div className="caption-kicker">Лия</div><h1>{labels[state]}</h1><p>{state==='listening'?'Слушаю тебя':state==='thinking'?'Думаю о твоём вопросе':state==='speaking'?'Отвечаю тебе':'Рядом, когда нужно'}</p></div></section><section className="conversation"><div className="conversation-line"><span>{labels[state]}</span><button onClick={cancel}>Остановить</button></div><div className="message-stack">{messages.slice(-4).map(message=><article className={`message ${message.role}`} key={message.id}><span className="speaker">{message.role==='user'?'Вы':'Лия'}</span><p>{message.text}</p><time className="time">{message.time}</time></article>)}</div><div className="quick-row">{quick.map(question=><button key={question} onClick={()=>submit(question)}>{question}<span>→</span></button>)}</div><form onSubmit={event=>{event.preventDefault();submit()}}><button type="button" onMouseDown={start} onMouseUp={stop} className={`voice-button ${state==='listening'?'recording':''}`}>●</button><input value={input} onChange={event=>setInput(event.target.value)} placeholder="Напишите Лии…"/><button className="send" type="submit">→</button></form></section>{panel&&<aside className="drawer"><div className="drawer-head"><b>Память Лии</b><button onClick={()=>setPanel(false)}>×</button></div>{facts.map(fact=><div className="memory-fact" key={fact.id}><span>{fact.content}</span><button onClick={()=>send({type:'memory_delete',id:fact.id})}>×</button></div>)}<button className="clear" onClick={()=>send({type:'memory_list'})}>Обновить</button><p>Факты хранятся локально.</p></aside>}<footer className="footer">{metrics?`STT ${metrics.stt_ms}ms · LLM ${metrics.llm_ms}ms · TTS ${metrics.tts_ms}ms${latency?.total?` · p95 ${latency.total.p95}ms`:''}`:'Локальный режим · аудио не покидает устройство'}</footer></main>
}
