import {useEffect,useRef,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {LiyaSocket} from './api'
import type {Message,ServerEvent,State} from './types'
import './styles.css'

const labels:Record<State,string>={idle:'Готова к разговору',listening:'Слушаю тебя',thinking:'Думаю',speaking:'Отвечаю',error:'Нужна помощь'}
const quickActions=['Что ты умеешь?','Составь план на день','Открой мои заметки','Запомни это']
function App(){
 const [state,setState]=useState<State>('idle');const [input,setInput]=useState('');const [active,setActive]=useState('conversation');const [connected,setConnected]=useState(false);const [muted,setMuted]=useState(false)
 const [messages,setMessages]=useState<Message[]>([{id:'welcome',role:'assistant',text:'Привет. Я Лия. Я рядом и готова помочь.',time:'09:41'}]);const socket=useRef(new LiyaSocket())
 const send=(event:unknown)=>{socket.current.connect();setTimeout(()=>socket.current.send(event),50)}
 useEffect(()=>{const s=socket.current;s.onOpen(()=>setConnected(true));s.onClose(()=>setConnected(false));s.onMessage((e:ServerEvent)=>{if(e.type==='state')setState(e.state);if(e.type==='transcript'&&e.text)setMessages(m=>[...m,{id:crypto.randomUUID(),role:'user',text:e.text,time:'сейчас'}]);if(e.type==='assistant_text')setMessages(m=>[...m,{id:crypto.randomUUID(),role:'assistant',text:e.text,time:'сейчас'}]);if(e.type==='error')setState('error')});s.connect();return()=>s.close()},[])
 const submit=(value=input)=>{const text=value.trim();if(!text)return;setMessages(m=>[...m,{id:crypto.randomUUID(),role:'user',text,time:'сейчас'}]);send({type:'text',text});setInput('')}
 const clear=()=>setMessages([{id:crypto.randomUUID(),role:'assistant',text:'Новый разговор. С чего начнём?',time:'сейчас'}])
 return <main className="app-shell">
  <aside className="sidebar"><div className="side-brand"><div className="liya-mark">Л</div><div><strong>Лия</strong><span>companion OS</span></div></div><nav><button className={active==='conversation'?'active':''} onClick={()=>setActive('conversation')}>◌ <span>Разговор</span><em>1</em></button><button className={active==='history'?'active':''} onClick={()=>setActive('history')}>◷ <span>История</span></button><button className={active==='notes'?'active':''} onClick={()=>setActive('notes')}>□ <span>Заметки</span></button><button className={active==='tools'?'active':''} onClick={()=>setActive('tools')}>⌘ <span>Инструменты</span></button></nav><div className="side-spacer"/><div className="privacy"><i/>Локальный режим<small>Данные не покидают устройство</small></div><div className="profile"><span className="avatar">Я</span><span><b>Я</b><small>Владелец</small></span><em>•••</em></div></aside>
  <section className="workspace"><header className="topbar"><div className="crumb">Рабочее пространство <b>/</b> <strong>{active}</strong></div><div className="top-actions"><div className="model-pill"><i className={connected?'live':'off'}/>{connected?'Все системы готовы':'Runtime не подключён'}⌄</div><button>⌘</button><button>?</button></div></header><div className="content">
   <section className="conversation-panel"><div className="conversation-head"><div><small>СЕЙЧАС</small><h1>Разговор с Лией</h1></div><button className="clear" onClick={clear}>Очистить</button></div><div className="presence"><div className={`presence-orb ${state}`}><span/></div><div><strong>{labels[state]}</strong><small>{state==='listening'?'Ваш голос передаётся локально':'Ваш локальный компаньон'}</small></div><div className="waveform">{[18,28,14,34,22,42,25,16,31,20,12,26].map((h,i)=><i key={i} style={{height:h}}/>)}</div></div><div className="messages">{messages.map(m=><article className={`message ${m.role}`} key={m.id}><div className="message-meta"><b>{m.role==='user'?'Вы':'Лия'}</b><time>{m.time}</time></div><p>{m.text}</p>{m.role==='assistant'&&<div className="message-tools"><button>♡</button><button>↗</button><button>•••</button></div>}</article>)}</div><div className="composer"><div className="composer-tools"><button className={muted?'active':''} onClick={()=>setMuted(!muted)}>⌘</button><button>＋</button><span>Только локальные модели</span></div><div className="composer-row"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')submit()}} placeholder="Напишите или скажите что-нибудь…"/><button className="mic" onMouseDown={()=>send({type:'start_listening'})} onMouseUp={()=>send({type:'stop_listening'})}>◉</button><button className="send" onClick={()=>submit()}>↑</button></div><div className="composer-hint"><span>↵ Отправить</span><span>·</span><span>Shift ↵ Новая строка</span><b>⌘ Локально</b></div></div></section>
   <aside className="right-panel"><section><div className="section-title"><span>Быстрые действия</span><button>•••</button></div><div className="quick-grid">{quickActions.map((q,i)=><button key={q} onClick={()=>submit(q)}><span className={`quick-icon qi${i}`}>{['✦','◫','⌁','♡'][i]}</span><span>{q}</span><b>↗</b></button>)}</div></section><section><div className="section-title"><span>Модели</span><button>Настроить</button></div><div className="model-card"><div className="model-avatar">Q</div><div><b>Qwen 3 · 8B</b><small>Локальная · 4-bit</small></div><i/></div><div className="model-card"><div className="model-avatar whisper">W</div><div><b>Whisper Turbo</b><small>STT · готова</small></div><i/></div><div className="model-card"><div className="model-avatar voice">♪</div><div><b>Голос Лии</b><small>Piper · 24 kHz</small></div><i/></div></section><section className="note"><div>✦</div><b>Маленькая мысль</b><p>Иногда лучший ответ — не самый длинный.</p><button>Добавить в заметки ↗</button></section></aside>
  </div><footer className="statusbar"><span><i/>Лия работает локально</span><span>Последняя синхронизация: только что</span><b>⌘ K  Команды</b></footer></section>
 </main>
}
createRoot(document.getElementById('root')!).render(<App/>)