import {useEffect,useRef,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {LiyaSocket} from './api'
import type {Message,ServerEvent,State} from './types'
import {LiaAvatar} from './LiaAvatar'
import './styles.css'

const labels:Record<State,string>={idle:'Р В РІР‚С”Р В РЎвЂР РЋР РЏ Р РЋР вЂљР РЋР РЏР В РўвЂР В РЎвЂўР В РЎВ',listening:'Р В Р Р‹Р В Р’В»Р РЋРЎвЂњР РЋРІвЂљВ¬Р В Р’В°Р РЋР вЂ№ Р РЋРІР‚С™Р В Р’ВµР В Р’В±Р РЋР РЏ',thinking:'Р В РІР‚СњР РЋРЎвЂњР В РЎВР В Р’В°Р РЋР вЂ№ Р В РЎвЂў Р РЋРІР‚С™Р В Р вЂ Р В РЎвЂўР РЋРІР‚ВР В РЎВ Р В Р’В·Р В Р’В°Р В РЎвЂ”Р РЋР вЂљР В РЎвЂўР РЋР С“Р В Р’Вµ',speaking:'Р В РЎвЂєР РЋРІР‚С™Р В Р вЂ Р В Р’ВµР РЋРІР‚РЋР В Р’В°Р РЋР вЂ№ Р РЋРІР‚С™Р В Р’ВµР В Р’В±Р В Р’Вµ',error:'Р В РЎСљР РЋРЎвЂњР В Р’В¶Р В Р вЂ¦Р В Р’В° Р В РЎвЂ”Р В РЎвЂўР В РЎВР В РЎвЂўР РЋРІР‚В°Р РЋР Р‰'}
const quick=['Р В Р’В§Р РЋРІР‚С™Р В РЎвЂў Р РЋРІР‚С™Р РЋРІР‚в„– Р РЋРЎвЂњР В РЎВР В Р’ВµР В Р’ВµР РЋРІвЂљВ¬Р РЋР Р‰?','Р В Р’В Р В Р’В°Р РЋР С“Р РЋР С“Р В РЎвЂќР В Р’В°Р В Р’В¶Р В РЎвЂ Р В РЎвЂў Р РЋР С“Р В Р’ВµР В Р’В±Р В Р’Вµ','Р В Р Р‹Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р В Р’В°Р В Р вЂ Р РЋР Р‰ Р В РЎвЂ”Р В Р’В»Р В Р’В°Р В Р вЂ¦ Р В Р вЂ¦Р В Р’В° Р В РўвЂР В Р’ВµР В Р вЂ¦Р РЋР Р‰','Р В РІР‚вЂќР В Р’В°Р В РЎвЂ”Р В РЎвЂўР В РЎВР В Р вЂ¦Р В РЎвЂ Р РЋР РЉР РЋРІР‚С™Р В РЎвЂў']

function App(){
 const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const requestId=useRef(0);const audioRef=useRef<HTMLAudioElement>(null)
 const vadContext=useRef<AudioContext|null>(null);const vadAnalyser=useRef<AnalyserNode|null>(null);const vadFrame=useRef<number|null>(null);const vadStarted=useRef(false);const vadSilentMs=useRef(0);const vadLastMs=useRef(0)
 const pcmNode=useRef<AudioWorkletNode|null>(null);const pcmSource=useRef<MediaStreamAudioSourceNode|null>(null)
  const audioContext=useRef<AudioContext|null>(null);const nextAudioAt=useRef(0)
  const [state,setState]=useState<State>('idle');const [metrics,setMetrics]=useState<{stt_ms:number;llm_ms:number;tts_ms:number;total_ms:number;preemptive_used:boolean}|null>(null);const [memoryFacts,setMemoryFacts]=useState<{id:number;kind:string;content:string;source:string}[]>([]);const [input,setInput]=useState('');const [messages,setMessages]=useState<Message[]>([{id:'hi',role:'assistant',text:'Привет. Я Лия. Рада, что ты здесь.' ,time:'сейчас'}]);const [panel,setPanel]=useState(false);const [connected,setConnected]=useState(false);const socket=useRef(new LiyaSocket())
 const send=(event:unknown)=>{socket.current.connect();setTimeout(()=>socket.current.send(event),50)}
 const startRecording=async()=>{if(recorder.current?.state==='recording')return;try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm;codecs=opus','audio/webm','audio/ogg'].find(m=>MediaRecorder.isTypeSupported(m))||'';recorder.current=new MediaRecorder(stream.current,mime?{mimeType:mime}:undefined);requestId.current=Date.now();recorder.current.ondataavailable=async e=>{if(e.data.size)send({type:'audio_chunk',request_id:requestId.current,data:arrayBufferToBase64(await e.data.arrayBuffer()),format:mime.includes('ogg')?'ogg':'webm'})};recorder.current.onstop=()=>{stream.current?.getTracks().forEach(t=>t.stop());send({type:'finish_listening',request_id:requestId.current,format:mime.includes('ogg')?'ogg':'webm'})};recorder.current.start(200);send({type:'start_listening',request_id:requestId.current})}catch{setState('error')}}
 const stopRecording=()=>recorder.current?.state==='recording'&&recorder.current.stop()
 const playAudio=(data:string,mime:string)=>{if(audioRef.current){audioRef.current.src=`data:${mime};base64,${data}`;void audioRef.current.play().catch(()=>{})}}
 const arrayBufferToBase64=(buffer:ArrayBuffer)=>{let binary='';const bytes=new Uint8Array(buffer);for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary)}
 useEffect(()=>{const s=socket.current;s.onOpen(()=>setConnected(true));s.onClose(()=>setConnected(false));s.onMessage((e:ServerEvent)=>{if(e.type==='state')setState(e.state);if(e.type==='pipeline_metrics')setMetrics(e);if(e.type==='memory'&&e.facts)setMemoryFacts(e.facts);if(e.type==='partial_transcript'){setState('thinking');setMessages(m=>{const last=m[m.length-1];return last?.role==='user'&&last.id==='interim'?m.map(x=>x.id==='interim'?{...x,text:e.text}:x):[...m,{id:'interim',role:'user',text:e.text,time:'РЎРѓР ВµР в„–РЎвЂЎР В°РЎРѓ'}]})}if(e.type==='transcript'&&e.text)setMessages(m=>{const last=m[m.length-1];return last?.id==='interim'?m.map(x=>x.id==='interim'?{...x,id:crypto.randomUUID(),text:e.text}:x):[...m,{id:crypto.randomUUID(),role:'user',text:e.text,time:'РЎРѓР ВµР в„–РЎвЂЎР В°РЎРѓ'}]});if(e.type==='assistant_chunk')setMessages(m=>{const last=m[m.length-1];return last?.role==='assistant'&&last.id==='streaming'?m.map(x=>x.id==='streaming'?{...x,text:e.text}:x):[...m,{id:'streaming',role:'assistant',text:e.text,time:'Р РЋР С“Р В Р’ВµР В РІвЂћвЂ“Р РЋРІР‚РЋР В Р’В°Р РЋР С“'}]});if(e.type==='assistant_text')setMessages(m=>{const last=m[m.length-1];return last?.id==='streaming'?m.map(x=>x.id==='streaming'?{...x,id:crypto.randomUUID(),text:e.text}:x):[...m,{id:crypto.randomUUID(),role:'assistant',text:e.text,time:'Р РЋР С“Р В Р’ВµР В РІвЂћвЂ“Р РЋРІР‚РЋР В Р’В°Р РЋР С“'}]});if(e.type==='cancelled')setMessages(m=>m.map(x=>x.id==='streaming'?{...x,id:crypto.randomUUID()}:x));if(e.type==='audio')playAudio(e.data,e.mime);if(e.type==='error')setState('error')});s.connect();return()=>s.close()},[])
  const stopResponse=()=>{if(audioRef.current)audioRef.current.pause();send({type:'cancel'})}
 const submit=(value=input)=>{const text=value.trim();if(!text)return;setMessages(m=>[...m,{id:crypto.randomUUID(),role:'user',text,time:'Р РЋР С“Р В Р’ВµР В РІвЂћвЂ“Р РЋРІР‚РЋР В Р’В°Р РЋР С“'}]);send({type:'text',text});setInput('')}
 return <main className={`companion ${state}`}>
  <header className="topbar"><div className="wordmark"><span className="wordmark-dot"/>Р В Р’В»Р В РЎвЂ<span>Р РЋР РЏ</span></div><div className="top-center">{connected?'Р Р†РІР‚вЂќР РЏ Р В Р’В»Р В РЎвЂўР В РЎвЂќР В Р’В°Р В Р’В»Р РЋР Р‰Р В Р вЂ¦Р В Р’В°Р РЋР РЏ Р РЋР С“Р В Р вЂ Р РЋР РЏР В Р’В·Р РЋР Р‰':'Р Р†РІР‚вЂќРІР‚в„– Р В РЎвЂўР В Р’В¶Р В РЎвЂР В РўвЂР В Р’В°Р В Р’ВµР РЋРІР‚С™ runtime'}</div><div className="top-actions"><button onClick={()=>setPanel(!panel)}>Р Р†Р’ВР’В°</button><button>Р Р†РЎв„ўРІвЂћСћ</button><div className="avatar">Р В Р вЂЎ</div></div></header>
  <section className="stage"><div className="stage-glow"/><LiaAvatar state={state} audioRef={audioRef}/><div className="character-shadow"/><div className="stage-caption"><div className="caption-kicker">Р В РІР‚С”Р В Р’ВР В Р вЂЎ</div><h1>{labels[state]}</h1><p>{state==='listening'?'Р В РІР‚СљР В РЎвЂўР В Р вЂ Р В РЎвЂўР РЋР вЂљР В РЎвЂ Р РЋР С“Р В Р вЂ Р В РЎвЂўР В Р’В±Р В РЎвЂўР В РўвЂР В Р вЂ¦Р В РЎвЂў Р Р†Р вЂљРІР‚Сњ Р РЋР РЏ Р В РЎвЂ”Р В РЎвЂўР В РІвЂћвЂ“Р В РЎВР РЋРЎвЂњ Р РЋРІР‚С™Р В Р’ВµР В Р’В±Р РЋР РЏ':state==='thinking'?'Р В Р Р‹Р В РЎвЂўР В Р’В±Р В РЎвЂР РЋР вЂљР В Р’В°Р РЋР вЂ№ Р В РЎВР РЋРІР‚в„–Р РЋР С“Р В Р’В»Р В РЎвЂ Р В Р вЂ  Р РЋР С“Р В Р’В»Р В РЎвЂўР В Р вЂ Р В Р’В°':'Р В Р вЂЎ Р В Р вЂ Р РЋР С“Р В Р’ВµР В РЎвЂ“Р В РўвЂР В Р’В° Р В РЎвЂ“Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂўР В Р вЂ Р В Р’В° Р В Р вЂ Р РЋРІР‚в„–Р РЋР С“Р В Р’В»Р РЋРЎвЂњР РЋРІвЂљВ¬Р В Р’В°Р РЋРІР‚С™Р РЋР Р‰'}</p></div></section>
   {metrics&&<div className="metrics">STT {metrics.stt_ms}ms Р’В· LLM {metrics.llm_ms}ms Р’В· TTS {metrics.tts_ms}ms Р’В· {metrics.preemptive_used?'РЎвЂЎР ВµРЎР‚Р Р…Р С•Р Р†Р С‘Р С” Р С‘РЎРѓР С—Р С•Р В»РЎРЉР В·Р С•Р Р†Р В°Р Р…':'Р С•РЎвЂљР Р†Р ВµРЎвЂљ Р С—Р ВµРЎР‚Р ВµРЎРѓР С•Р В±РЎР‚Р В°Р Р…'}</div>}
  <section className="conversation"><div className="conversation-line"><button onClick={()=>send({type:'memory_list'})}>РџР°РјСЏС‚СЊ: {memoryFacts.length}</button><span>Р В РІР‚в„ўР В Р’В°Р РЋРІвЂљВ¬ Р РЋР вЂљР В Р’В°Р В Р’В·Р В РЎвЂ“Р В РЎвЂўР В Р вЂ Р В РЎвЂўР РЋР вЂљ</span><button onClick={stopResponse}>Р В РЎвЂєР РЋР С“Р РЋРІР‚С™Р В Р’В°Р В Р вЂ¦Р В РЎвЂўР В Р вЂ Р В РЎвЂР РЋРІР‚С™Р РЋР Р‰</button></div><div className="message-stack">{messages.slice(-4).map(m=><article className={`message ${m.role}`} key={m.id}><span className="speaker">{m.role==='user'?'Р В Р вЂ Р РЋРІР‚в„–':'Р В Р’В»Р В РЎвЂР РЋР РЏ'}</span><p>{m.text}</p><time>{m.time}</time></article>)}</div><div className="quick-row">{quick.map(q=><button key={q} onClick={()=>submit(q)}>{q}<span>Р Р†РІР‚В РІР‚вЂќ</span></button>)}</div><form onSubmit={e=>{e.preventDefault();submit()}}><audio ref={audioRef}/><button type="button" onMouseDown={startRecording} onMouseUp={stopRecording} className={state==='listening'?'voice-button recording':'voice-button'}>Р Р†РІР‚вЂќРІР‚В°</button><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Р В Р Р‹Р В РЎвЂќР В Р’В°Р В Р’В¶Р В РЎвЂ Р РЋРІР‚РЋР РЋРІР‚С™Р В РЎвЂў-Р В Р вЂ¦Р В РЎвЂР В Р’В±Р РЋРЎвЂњР В РўвЂР РЋР Р‰ Р В РЎвЂР В Р’В»Р В РЎвЂ Р В Р вЂ¦Р В Р’В°Р В РЎвЂ”Р В РЎвЂР РЋРІвЂљВ¬Р В РЎвЂР Р†Р вЂљР’В¦"/><button className="send" type="submit">Р Р†РІР‚В РІР‚В</button></form></section>
  {panel&&<aside className="drawer"><div className="drawer-head"><b>Р В РІР‚С”Р В РЎвЂР РЋР РЏ</b><button onClick={()=>setPanel(false)}>Р вЂњРІР‚вЂќ</button></div><p>Р В РЎС›Р В Р вЂ Р В РЎвЂўР В РІвЂћвЂ“ Р В Р’В»Р В РЎвЂўР В РЎвЂќР В Р’В°Р В Р’В»Р РЋР Р‰Р В Р вЂ¦Р РЋРІР‚в„–Р В РІвЂћвЂ“ Р В РЎвЂќР В РЎвЂўР В РЎВР В РЎвЂ”Р В Р’В°Р В Р вЂ¦Р РЋР Р‰Р В РЎвЂўР В Р вЂ¦. Р В РІР‚в„ўР РЋР С“Р РЋРІР‚В, Р РЋРІР‚РЋР РЋРІР‚С™Р В РЎвЂў Р РЋРІР‚С™Р РЋРІР‚в„– Р В РЎвЂ“Р В РЎвЂўР В Р вЂ Р В РЎвЂўР РЋР вЂљР В РЎвЂР РЋРІвЂљВ¬Р РЋР Р‰, Р В РЎвЂўР РЋР С“Р РЋРІР‚С™Р В Р’В°Р РЋРІР‚ВР РЋРІР‚С™Р РЋР С“Р РЋР РЏ Р В Р вЂ¦Р В Р’В° Р РЋР РЉР РЋРІР‚С™Р В РЎвЂўР В РЎВ Р РЋРЎвЂњР РЋР С“Р РЋРІР‚С™Р РЋР вЂљР В РЎвЂўР В РІвЂћвЂ“Р РЋР С“Р РЋРІР‚С™Р В Р вЂ Р В Р’Вµ.</p><div className="drawer-item"><span>Р В РЎСљР В Р’В°Р РЋР С“Р РЋРІР‚С™Р РЋР вЂљР В РЎвЂўР В Р’ВµР В Р вЂ¦Р В РЎвЂР В Р’Вµ</span><b>Р В Р Р‹Р В РЎвЂ”Р В РЎвЂўР В РЎвЂќР В РЎвЂўР В РІвЂћвЂ“Р В Р вЂ¦Р В Р’В°Р РЋР РЏ Р В РЎвЂ Р В Р вЂ Р В Р вЂ¦Р В РЎвЂР В РЎВР В Р’В°Р РЋРІР‚С™Р В Р’ВµР В Р’В»Р РЋР Р‰Р В Р вЂ¦Р В Р’В°Р РЋР РЏ</b></div><div className="drawer-item"><span>Р В РЎСџР В Р’В°Р В РЎВР РЋР РЏР РЋРІР‚С™Р РЋР Р‰</span><b>Р В РЎС›Р В РЎвЂўР В Р’В»Р РЋР Р‰Р В РЎвЂќР В РЎвЂў Р РЋРІР‚С™Р В РЎвЂў, Р РЋРІР‚РЋР РЋРІР‚С™Р В РЎвЂў Р РЋР вЂљР В Р’В°Р В Р’В·Р РЋР вЂљР В Р’ВµР РЋРІвЂљВ¬Р В РЎвЂР РЋРІвЂљВ¬Р РЋР Р‰</b></div><div className="drawer-item"><span>Р В РІР‚СљР В РЎвЂўР В Р’В»Р В РЎвЂўР РЋР С“</span><b>Р В РІР‚С”Р В РЎвЂўР В РЎвЂќР В Р’В°Р В Р’В»Р РЋР Р‰Р В Р вЂ¦Р РЋРІР‚в„–Р В РІвЂћвЂ“ Р вЂ™Р’В· Р В РЎвЂ“Р В РЎвЂўР РЋРІР‚С™Р В РЎвЂўР В Р вЂ  Р В РЎвЂќ Р В РЎвЂ”Р В РЎвЂўР В РўвЂР В РЎвЂќР В Р’В»Р РЋР вЂ№Р РЋРІР‚РЋР В Р’ВµР В Р вЂ¦Р В РЎвЂР РЋР вЂ№</b></div><div className="drawer-foot">Esc Р вЂ™Р’В· Р В Р’В·Р В Р’В°Р В РЎвЂќР РЋР вЂљР РЋРІР‚в„–Р РЋРІР‚С™Р РЋР Р‰</div></aside>}
   {panel&&<aside className="drawer"><div className="drawer-head"><b>Лия</b><button onClick={()=>setPanel(false)}>×</button></div><div className="drawer-item"><span>Память</span><b>{memoryFacts.length} фактов</b><button className="clear" onClick={()=>send({type:'memory_list'})}>Обновить</button></div>{memoryFacts.map(fact=><div className="memory-fact" key={fact.id}><span>{fact.content}</span><button onClick={()=>send({type:'memory_delete',id:fact.id})}>×</button></div>)}<p>Всё, что ты говоришь, остаётся на этом устройстве.</p><div className="drawer-item"><span>Настроение</span><b>Спокойная и внимательная</b></div><div className="drawer-item"><span>Голос</span><b>Локальный · готов к подключению</b></div><div className="drawer-foot">Esc · закрыть</div></aside>}
  <footer className="footer"><span>Р Р†Р Р‰Р’В K Р В Р’В±Р РЋРІР‚в„–Р РЋР С“Р РЋРІР‚С™Р РЋР вЂљР РЋРІР‚в„–Р В Р’Вµ Р В РЎвЂќР В РЎвЂўР В РЎВР В Р’В°Р В Р вЂ¦Р В РўвЂР РЋРІР‚в„–</span><span>Р В РІР‚С”Р В РЎвЂР РЋР РЏ v0.1 Р вЂ™Р’В· Р В Р’В»Р В РЎвЂўР В РЎвЂќР В Р’В°Р В Р’В»Р РЋР Р‰Р В Р вЂ¦Р РЋРІР‚в„–Р В РІвЂћвЂ“ Р РЋР вЂљР В Р’ВµР В Р’В¶Р В РЎвЂР В РЎВ</span><span>Р В РЎСљР В РЎвЂР РЋРІР‚РЋР В Р’ВµР В РЎвЂ“Р В РЎвЂў Р В Р’В»Р В РЎвЂР РЋРІвЂљВ¬Р В Р вЂ¦Р В Р’ВµР В РЎвЂ“Р В РЎвЂў</span></footer>
 </main>
}
createRoot(document.getElementById('root')!).render(<App/>)
