import {useEffect,useRef,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {LiyaSocket} from './api'
import type {Message,ServerEvent,State} from './types'
import {LiaAvatar} from './LiaAvatar'
import './styles.css'

const labels:Record<State,string>={idle:'Р вЂєР С‘РЎРЏ РЎР‚РЎРЏР Т‘Р С•Р С',listening:'Р РЋР В»РЎС“РЎв‚¬Р В°РЎР‹ РЎвЂљР ВµР В±РЎРЏ',thinking:'Р вЂќРЎС“Р СР В°РЎР‹ Р С• РЎвЂљР Р†Р С•РЎвЂР С Р В·Р В°Р С—РЎР‚Р С•РЎРѓР Вµ',speaking:'Р С›РЎвЂљР Р†Р ВµРЎвЂЎР В°РЎР‹ РЎвЂљР ВµР В±Р Вµ',error:'Р СњРЎС“Р В¶Р Р…Р В° Р С—Р С•Р СР С•РЎвЂ°РЎРЉ'}
const quick=['Р В§РЎвЂљР С• РЎвЂљРЎвЂ№ РЎС“Р СР ВµР ВµРЎв‚¬РЎРЉ?','Р В Р В°РЎРѓРЎРѓР С”Р В°Р В¶Р С‘ Р С• РЎРѓР ВµР В±Р Вµ','Р РЋР С•РЎРѓРЎвЂљР В°Р Р†РЎРЉ Р С—Р В»Р В°Р Р… Р Р…Р В° Р Т‘Р ВµР Р…РЎРЉ','Р вЂ”Р В°Р С—Р С•Р СР Р…Р С‘ РЎРЊРЎвЂљР С•']

function App(){
 const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const requestId=useRef(0);const audioRef=useRef<HTMLAudioElement>(null)
 const vadContext=useRef<AudioContext|null>(null);const vadAnalyser=useRef<AnalyserNode|null>(null);const vadFrame=useRef<number|null>(null);const vadStarted=useRef(false);const vadSilentMs=useRef(0);const vadLastMs=useRef(0)
 const pcmNode=useRef<AudioWorkletNode|null>(null);const pcmSource=useRef<MediaStreamAudioSourceNode|null>(null)
  const audioContext=useRef<AudioContext|null>(null);const nextAudioAt=useRef(0)
  const [state,setState]=useState<State>('idle');const [metrics,setMetrics]=useState<{stt_ms:number;llm_ms:number;tts_ms:number;total_ms:number;preemptive_used:boolean}|null>(null);const [input,setInput]=useState('');const [messages,setMessages]=useState<Message[]>([{id:'hi',role:'assistant',text:'Привет. Я Лия. Рада, что ты здесь.' ,time:'сейчас'}]);const [panel,setPanel]=useState(false);const [connected,setConnected]=useState(false);const socket=useRef(new LiyaSocket())
 const send=(event:unknown)=>{socket.current.connect();setTimeout(()=>socket.current.send(event),50)}
 const startRecording=async()=>{if(recorder.current?.state==='recording')return;try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm;codecs=opus','audio/webm','audio/ogg'].find(m=>MediaRecorder.isTypeSupported(m))||'';recorder.current=new MediaRecorder(stream.current,mime?{mimeType:mime}:undefined);requestId.current=Date.now();recorder.current.ondataavailable=async e=>{if(e.data.size)send({type:'audio_chunk',request_id:requestId.current,data:arrayBufferToBase64(await e.data.arrayBuffer()),format:mime.includes('ogg')?'ogg':'webm'})};recorder.current.onstop=()=>{stream.current?.getTracks().forEach(t=>t.stop());send({type:'finish_listening',request_id:requestId.current,format:mime.includes('ogg')?'ogg':'webm'})};recorder.current.start(200);send({type:'start_listening',request_id:requestId.current})}catch{setState('error')}}
 const stopRecording=()=>recorder.current?.state==='recording'&&recorder.current.stop()
 const playAudio=(data:string,mime:string)=>{if(audioRef.current){audioRef.current.src=`data:${mime};base64,${data}`;void audioRef.current.play().catch(()=>{})}}
 const arrayBufferToBase64=(buffer:ArrayBuffer)=>{let binary='';const bytes=new Uint8Array(buffer);for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary)}
 useEffect(()=>{const s=socket.current;s.onOpen(()=>setConnected(true));s.onClose(()=>setConnected(false));s.onMessage((e:ServerEvent)=>{if(e.type==='state')setState(e.state);if(e.type==='pipeline_metrics')setMetrics(e);if(e.type==='partial_transcript'){setState('thinking');setMessages(m=>{const last=m[m.length-1];return last?.role==='user'&&last.id==='interim'?m.map(x=>x.id==='interim'?{...x,text:e.text}:x):[...m,{id:'interim',role:'user',text:e.text,time:'СЃРµР№С‡Р°СЃ'}]})}if(e.type==='transcript'&&e.text)setMessages(m=>{const last=m[m.length-1];return last?.id==='interim'?m.map(x=>x.id==='interim'?{...x,id:crypto.randomUUID(),text:e.text}:x):[...m,{id:crypto.randomUUID(),role:'user',text:e.text,time:'СЃРµР№С‡Р°СЃ'}]});if(e.type==='assistant_chunk')setMessages(m=>{const last=m[m.length-1];return last?.role==='assistant'&&last.id==='streaming'?m.map(x=>x.id==='streaming'?{...x,text:e.text}:x):[...m,{id:'streaming',role:'assistant',text:e.text,time:'РЎРѓР ВµР в„–РЎвЂЎР В°РЎРѓ'}]});if(e.type==='assistant_text')setMessages(m=>{const last=m[m.length-1];return last?.id==='streaming'?m.map(x=>x.id==='streaming'?{...x,id:crypto.randomUUID(),text:e.text}:x):[...m,{id:crypto.randomUUID(),role:'assistant',text:e.text,time:'РЎРѓР ВµР в„–РЎвЂЎР В°РЎРѓ'}]});if(e.type==='cancelled')setMessages(m=>m.map(x=>x.id==='streaming'?{...x,id:crypto.randomUUID()}:x));if(e.type==='audio')playAudio(e.data,e.mime);if(e.type==='error')setState('error')});s.connect();return()=>s.close()},[])
  const stopResponse=()=>{if(audioRef.current)audioRef.current.pause();send({type:'cancel'})}
 const submit=(value=input)=>{const text=value.trim();if(!text)return;setMessages(m=>[...m,{id:crypto.randomUUID(),role:'user',text,time:'РЎРѓР ВµР в„–РЎвЂЎР В°РЎРѓ'}]);send({type:'text',text});setInput('')}
 return <main className={`companion ${state}`}>
  <header className="topbar"><div className="wordmark"><span className="wordmark-dot"/>Р В»Р С‘<span>РЎРЏ</span></div><div className="top-center">{connected?'РІвЂ”РЏ Р В»Р С•Р С”Р В°Р В»РЎРЉР Р…Р В°РЎРЏ РЎРѓР Р†РЎРЏР В·РЎРЉ':'РІвЂ”вЂ№ Р С•Р В¶Р С‘Р Т‘Р В°Р ВµРЎвЂљ runtime'}</div><div className="top-actions"><button onClick={()=>setPanel(!panel)}>РІВВ°</button><button>РІС™в„ў</button><div className="avatar">Р Р‡</div></div></header>
  <section className="stage"><div className="stage-glow"/><LiaAvatar state={state} audioRef={audioRef}/><div className="character-shadow"/><div className="stage-caption"><div className="caption-kicker">Р вЂєР ВР Р‡</div><h1>{labels[state]}</h1><p>{state==='listening'?'Р вЂњР С•Р Р†Р С•РЎР‚Р С‘ РЎРѓР Р†Р С•Р В±Р С•Р Т‘Р Р…Р С• РІР‚вЂќ РЎРЏ Р С—Р С•Р в„–Р СРЎС“ РЎвЂљР ВµР В±РЎРЏ':state==='thinking'?'Р РЋР С•Р В±Р С‘РЎР‚Р В°РЎР‹ Р СРЎвЂ№РЎРѓР В»Р С‘ Р Р† РЎРѓР В»Р С•Р Р†Р В°':'Р Р‡ Р Р†РЎРѓР ВµР С–Р Т‘Р В° Р С–Р С•РЎвЂљР С•Р Р†Р В° Р Р†РЎвЂ№РЎРѓР В»РЎС“РЎв‚¬Р В°РЎвЂљРЎРЉ'}</p></div></section>
   {metrics&&<div className="metrics">STT {metrics.stt_ms}ms В· LLM {metrics.llm_ms}ms В· TTS {metrics.tts_ms}ms В· {metrics.preemptive_used?'С‡РµСЂРЅРѕРІРёРє РёСЃРїРѕР»СЊР·РѕРІР°РЅ':'РѕС‚РІРµС‚ РїРµСЂРµСЃРѕР±СЂР°РЅ'}</div>}
  <section className="conversation"><div className="conversation-line"><span>Р вЂ™Р В°РЎв‚¬ РЎР‚Р В°Р В·Р С–Р С•Р Р†Р С•РЎР‚</span><button onClick={stopResponse}>Р С›РЎРѓРЎвЂљР В°Р Р…Р С•Р Р†Р С‘РЎвЂљРЎРЉ</button></div><div className="message-stack">{messages.slice(-4).map(m=><article className={`message ${m.role}`} key={m.id}><span className="speaker">{m.role==='user'?'Р Р†РЎвЂ№':'Р В»Р С‘РЎРЏ'}</span><p>{m.text}</p><time>{m.time}</time></article>)}</div><div className="quick-row">{quick.map(q=><button key={q} onClick={()=>submit(q)}>{q}<span>РІвЂ вЂ”</span></button>)}</div><form onSubmit={e=>{e.preventDefault();submit()}}><audio ref={audioRef}/><button type="button" onMouseDown={startRecording} onMouseUp={stopRecording} className={state==='listening'?'voice-button recording':'voice-button'}>РІвЂ”вЂ°</button><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Р РЋР С”Р В°Р В¶Р С‘ РЎвЂЎРЎвЂљР С•-Р Р…Р С‘Р В±РЎС“Р Т‘РЎРЉ Р С‘Р В»Р С‘ Р Р…Р В°Р С—Р С‘РЎв‚¬Р С‘РІР‚В¦"/><button className="send" type="submit">РІвЂ вЂ</button></form></section>
  {panel&&<aside className="drawer"><div className="drawer-head"><b>Р вЂєР С‘РЎРЏ</b><button onClick={()=>setPanel(false)}>Р“вЂ”</button></div><p>Р СћР Р†Р С•Р в„– Р В»Р С•Р С”Р В°Р В»РЎРЉР Р…РЎвЂ№Р в„– Р С”Р С•Р СР С—Р В°Р Р…РЎРЉР С•Р Р…. Р вЂ™РЎРѓРЎвЂ, РЎвЂЎРЎвЂљР С• РЎвЂљРЎвЂ№ Р С–Р С•Р Р†Р С•РЎР‚Р С‘РЎв‚¬РЎРЉ, Р С•РЎРѓРЎвЂљР В°РЎвЂРЎвЂљРЎРѓРЎРЏ Р Р…Р В° РЎРЊРЎвЂљР С•Р С РЎС“РЎРѓРЎвЂљРЎР‚Р С•Р в„–РЎРѓРЎвЂљР Р†Р Вµ.</p><div className="drawer-item"><span>Р СњР В°РЎРѓРЎвЂљРЎР‚Р С•Р ВµР Р…Р С‘Р Вµ</span><b>Р РЋР С—Р С•Р С”Р С•Р в„–Р Р…Р В°РЎРЏ Р С‘ Р Р†Р Р…Р С‘Р СР В°РЎвЂљР ВµР В»РЎРЉР Р…Р В°РЎРЏ</b></div><div className="drawer-item"><span>Р СџР В°Р СРЎРЏРЎвЂљРЎРЉ</span><b>Р СћР С•Р В»РЎРЉР С”Р С• РЎвЂљР С•, РЎвЂЎРЎвЂљР С• РЎР‚Р В°Р В·РЎР‚Р ВµРЎв‚¬Р С‘РЎв‚¬РЎРЉ</b></div><div className="drawer-item"><span>Р вЂњР С•Р В»Р С•РЎРѓ</span><b>Р вЂєР С•Р С”Р В°Р В»РЎРЉР Р…РЎвЂ№Р в„– Р’В· Р С–Р С•РЎвЂљР С•Р Р† Р С” Р С—Р С•Р Т‘Р С”Р В»РЎР‹РЎвЂЎР ВµР Р…Р С‘РЎР‹</b></div><div className="drawer-foot">Esc Р’В· Р В·Р В°Р С”РЎР‚РЎвЂ№РЎвЂљРЎРЉ</div></aside>}
  <footer className="footer"><span>РІРЉВ K Р В±РЎвЂ№РЎРѓРЎвЂљРЎР‚РЎвЂ№Р Вµ Р С”Р С•Р СР В°Р Р…Р Т‘РЎвЂ№</span><span>Р вЂєР С‘РЎРЏ v0.1 Р’В· Р В»Р С•Р С”Р В°Р В»РЎРЉР Р…РЎвЂ№Р в„– РЎР‚Р ВµР В¶Р С‘Р С</span><span>Р СњР С‘РЎвЂЎР ВµР С–Р С• Р В»Р С‘РЎв‚¬Р Р…Р ВµР С–Р С•</span></footer>
 </main>
}
createRoot(document.getElementById('root')!).render(<App/>)
